import { useState, useEffect } from 'react'
import type { GeneratedIcon } from '@/types'
import { SvgPreview } from '@/components/svg/SvgPreview'
import { SvgCodeViewer } from '@/components/svg/SvgCodeViewer'
import { SvgActions } from '@/components/svg/SvgActions'
import { Button } from '@/components/common/Button'
import './styles.scss'

interface ResultPanelProps {
  icon: GeneratedIcon | null
  isGenerating: boolean
  error: string | null
  onRegenerate: () => void
  onClearError: () => void
}

const LOADING_STEPS = [
  'Understanding your description',
  'Designing vector geometry',
  'Generating SVG paths',
  'Validating SVG',
]

export function ResultPanel({
  icon,
  isGenerating,
  error,
  onRegenerate,
  onClearError,
}: ResultPanelProps) {
  const [activeStep, setActiveStep] = useState(0)
  const [completedSteps, setCompletedSteps] = useState<number[]>([])

  useEffect(() => {
    if (!isGenerating) {
      setActiveStep(0)
      setCompletedSteps([])
      return
    }

    const intervals: ReturnType<typeof setTimeout>[] = []

    LOADING_STEPS.forEach((_, i) => {
      const startDelay = i * 1200

      intervals.push(
        setTimeout(() => {
          setActiveStep(i)
        }, startDelay)
      )

      intervals.push(
        setTimeout(() => {
          setCompletedSteps((prev) => [...prev, i])
        }, startDelay + 1000)
      )
    })

    return () => intervals.forEach(clearTimeout)
  }, [isGenerating])

  return (
    <div className="result-panel">
      <div className="result-panel__header">
        <h2 className="result-panel__title">AI Generated Icon</h2>
      </div>

      <div className="result-panel__body">
        {/* Loading State */}
        {isGenerating && (
          <div className="result-panel__loading">
            <div className="result-panel__loading-icon">
              <div className="result-panel__loading-pulse" />
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" />
              </svg>
            </div>
            <h3 className="result-panel__loading-title">✨ AI is creating your icon...</h3>
            <div className="result-panel__steps">
              {LOADING_STEPS.map((step, i) => {
                const isComplete = completedSteps.includes(i)
                const isActive = activeStep === i && !isComplete

                return (
                  <div
                    key={i}
                    className={`result-panel__step ${isComplete ? 'result-panel__step--complete' : ''} ${isActive ? 'result-panel__step--active' : ''}`}
                  >
                    <span className="result-panel__step-status">
                      {isComplete ? '✓' : isActive ? '●' : '○'}
                    </span>
                    <span className="result-panel__step-label">{step}</span>
                  </div>
                )
              })}
            </div>
          </div>
        )}

        {/* Empty State */}
        {!isGenerating && !icon && !error && (
          <div className="result-panel__empty">
            <div className="result-panel__empty-icon">✨</div>
            <h3 className="result-panel__empty-title">Your AI-generated icon will appear here</h3>
            <p className="result-panel__empty-text">
              Describe any icon on the left and let AI turn your idea into a scalable SVG.
            </p>
          </div>
        )}

        {/* Error State */}
        {!isGenerating && error && (
          <div className="result-panel__error">
            <div className="result-panel__error-icon">⚠️</div>
            <h3 className="result-panel__error-title">Generation Failed</h3>
            <p className="result-panel__error-text">{error}</p>
            <Button variant="secondary" onClick={() => { onClearError(); onRegenerate() }}>
              Try Again
            </Button>
          </div>
        )}

        {/* Generated Result */}
        {!isGenerating && icon && (
          <div className="result-panel__result">
            <div className="result-panel__preview-container">
              <SvgPreview svg={icon.svg} title={icon.title} size="xl" />
            </div>

            <div className="result-panel__info">
              <h3 className="result-panel__info-title">{icon.title}</h3>
              <p className="result-panel__info-desc">{icon.description}</p>
              <div className="result-panel__info-meta">
                <span className="result-panel__info-style">
                  Style: {icon.style === 'fill' ? 'Fill' : 'Stroke'}
                </span>
                <span className="result-panel__info-ai">
                  ✓ Generated by AI
                </span>
              </div>
            </div>

            <SvgCodeViewer svg={icon.svg} />

            <div className="result-panel__actions">
              <SvgActions svg={icon.svg} prompt={icon.prompt} />
              <Button
                variant="ghost"
                size="sm"
                onClick={onRegenerate}
              >
                ↻ Regenerate
              </Button>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
